In [1]:
import numpy as np

In [2]:
s = np.array(5)

In [3]:
print (s)

5


In [4]:
s = s + 3

In [5]:
print (s)

8


In [6]:
print (s.shape)

()


In [8]:
print(type(s))

<class 'numpy.int64'>


In [9]:
v = np.array([1,2,3])

In [10]:
print (v)

[1 2 3]


In [11]:
print (v.shape)

(3,)


In [12]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])


In [13]:
print (m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [15]:
print (t)

[[[[ 1]
   [ 2]]

  [[ 3]
   [ 4]]

  [[ 5]
   [ 6]]]


 [[[ 7]
   [ 8]]

  [[ 9]
   [10]]

  [[11]
   [12]]]


 [[[13]
   [14]]

  [[15]
   [16]]

  [[17]
   [17]]]]


In [17]:
x = v.reshape(1,3)

In [18]:
print(x)

[[1 2 3]]


In [19]:
print (x.shape)

(1, 3)


In [22]:
values = [1,2,3,4,5]
values = np.array(values) + 5
print(values)

[ 6  7  8  9 10]


In [23]:
m = np.array([[1,2,3],[4,5,6]])
print (m)

[[1 2 3]
 [4 5 6]]


In [26]:
print (m * 10)
n = m * 10
print (m * n)

[[10 20 30]
 [40 50 60]]
[[ 10  40  90]
 [160 250 360]]


m * n

In [28]:
n = n.reshape(3,2)
print (n)

[[10 20]
 [30 40]
 [50 60]]


In [29]:
np.dot(m, n)

array([[220, 280],
       [490, 640]])

In [30]:
print(n.shape)

(3, 2)


In [33]:
(3,3) == (3,2)

False

In [34]:
def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max

In [35]:
def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[1] != m2.shape[0]:
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.dot(m1, m2)
    else:
        return np.dot(m2, m1)

In [36]:
def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    np.mean(values)

In [37]:
input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[ 0.     0.375  1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
False
Mean == None
